apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-microservicos-bv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-microservicos-bv
  template:
    metadata:
      labels:
        app: spring-microservicos-bv
    spec:
      containers:
        - name: spring-microservicos-bv
          image: us.gcr.io/{ID-PROJETO-GOOGLE}/spring-microservicos-bv:latest
          
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-microservicos-bv-service
spec:
  selector:
    app: spring-boot
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer